### ISSUE TITLE
【開発準備】タスクの管理方法が不明

### ISSUE THREAD

**Issue by seiya-takano** [WitStudy/PMSystem#1]
現状、タスクの管理方法を明確にしていない。
ひとまずのところissueに課題を挙げることで対応

**Comment by jz4o** [comment]
以下のようにして管理するのはいかがでしょうか

## 管理箇所・対象
* Issue　 ： 課題全体 
* Project ： 進捗状況のみ

## 管理方法

### 課題が発生したとき
* Issueを作成する

### Issueが作成されたとき
* 対応の要否をIssueにて検討する

### Issueの対応が不要となったとき
* IssueをCloseする

### Issueの対応が必要となったとき
* IssueにてAssigneesを設定する
* Issueを元にProjectにCardを作成する

### 作業を行うとき
* 作業状況に応じてCardを移動する

### Commitするとき
* Issueに紐付けてCommitする

### 担当者を変更するとき
* IssueにてAssigneesを修正する

### 対応が終了したとき
* ProjectからCardを削除する
* IssueをCloseする

**Comment by seiya-takano** [comment]
ちょっと整理させて..

タスク発生？
↓
issueへ登録
検討後、必要なものをcardに挙げタスクとして本採用
↓
タスク消化へ

ただ、コミット物への紐づけはissueに？
タスク単位でコミットってのはできないのかね？
なんとなく１つのissueから複数のcardが出そうだけど
そこらへんの粒度整える必要があるかもですね

**Comment by jz4o** [comment]
>タスク発生？
>↓
>issueへ登録
>検討後、必要なものをcardに挙げタスクとして本採用
>↓
>タスク消化へ

仰るとおりの想定です。

>ただ、コミット物への紐づけはissueに？

Cardはあくまで進捗状況の管理のみ、かつ、IssueをCloseする際に削除する想定でしたので、
コミットは課題全体を管理するIssueに紐づけてはどうかと思いました。
　※IssueはCloseした後も残り続ける（・・・はずです）

>タスク単位でコミットってのはできないのかね？

意図を掴めていない可能性が大いにありますが、
1つのIssueの作業中に複数のコミットを行いたいということでしたら、可能かと思います。
　※コミットではIssueへの紐付けのみ行い、IssueのClose等は行わない想定です

>なんとなく１つのissueから複数のcardが出そうだけど
>そこらへんの粒度整える必要があるかもですね

複数のCardから同一のIssueを参照するように設定することは可能なようですが、
Issue画面から参照できるCardは1つまでのようです。
よって、IssueとCardは1対1の関係にしておいた方が良いと考えます。

ですので、1つのIssueから、複数のCardを作成したくなった場合、
親Issue、子Issueのような形に分けてはどうでしょうか。
　※対応は子Issue単位で行い、全ての子Issueの対応が終了したら親IssueをCloseするイメージです

**Comment by seiya-takano** [comment]
時間が開いてしまい申し訳ありません、、

>Cardはあくまで進捗状況の管理のみ、かつ、IssueをCloseする際に削除する想定でしたので、
コミットは課題全体を管理するIssueに紐づけてはどうかと思いました。
　※IssueはCloseした後も残り続ける（・・・はずです）

IsuueとCardの役割分離の狙い理解しました。
Isuueクローズ後も残ることを確認しましたので、この想定で進めて問題ないよう思います

>複数のCardから同一のIssueを参照するように設定することは可能なようですが、
Issue画面から参照できるCardは1つまでのようです。
よって、IssueとCardは1対1の関係にしておいた方が良いと考えます。

>ですので、1つのIssueから、複数のCardを作成したくなった場合、
親Issue、子Issueのような形に分けてはどうでしょうか。
　※対応は子Issue単位で行い、全ての子Issueの対応が終了したら親IssueをCloseするイメージです

なるほど。Issueの分割案賛成です。
但し、初めから子issueが存在することが分かっていれば管理しやすそうですが
親Issue対応中に発覚し分割することになった場合少々面倒がありそうですね
親と子..というよりは同レベルの関連Issueとして管理できればと思いました。

**Comment by jz4o** [comment]
>なるほど。Issueの分割案賛成です。

ありがとうございます。

>但し、初めから子issueが存在することが分かっていれば管理しやすそうですが
親Issue対応中に発覚し分割することになった場合少々面倒がありそうですね
親と子..というよりは同レベルの関連Issueとして管理できればと思いました。

確かに対応中の分割はあまりしたくありませんね。。。
そのあたりは対応前に可能な範囲で、いくつのIssueで対応するか検討し、
対応中の分割が極力発生しないように気をつけたいですね。

**Comment by seiya-takano** [comment]
>そのあたりは対応前に可能な範囲で、いくつのIssueで対応するか検討し、
対応中の分割が極力発生しないように気をつけたいですね。

わかりました。事前のIssueの検討を心掛けていきましょう。
この辺は実際にIssueに直面してみないとなんとも言えませんね
当件、一旦クローズとしてもよろしいでしょうか？

**Comment by jz4o** [comment]
タスクの管理方法をどこかに残しておかなくて大丈夫でしょうか？

残さないのであれば、Closeで良いと思います。

**Comment by seiya-takano** [comment]
>タスクの管理方法をどこかに残しておかなくて大丈夫でしょうか？
残さないのであれば、Closeで良いと思います。

Issue #3 でも扱っていますし、記録しておきましょう。
本決まりしたらタスクとして登録をお願いできますか？

**Comment by jz4o** [comment]
>Issue #3 でも扱っていますし、記録しておきましょう。
本決まりしたらタスクとして登録をお願いできますか？

承知しました。
本Issueは #3 にてドキュメント記載の方針決定後、あらためて対応致しましょう。

**Comment by seiya-takano** [comment]
よろしくおねがいします。

**Comment by jz4o** [comment]
2017/09/27のミーティングにて検討しましたので、私のほうで以下対応を行います。

- タスクの管理方法をWikiに記載する。

**Comment by jz4o** [comment]
@seiya-takano 
Wikiに「タスクの管理」ページを作成しましたので、内容の確認をお願い致します。

**Comment by seiya-takano** [comment]
Wikiの更新ありがとうございました。

1点ほど気になった点を記載します。
本システム、動作OSを任意としていますが
DB設定ファイルのsocket初期設定値はCentOSのものかと思われます。
一言コメントがあると親切かと思いました。

（仮称となっているWikiタイトル問題がありましたら変更お願いします。。）

以上、よろしくお願い致します。

**Comment by jz4o** [comment]
確認及びご指摘いただき、ありがとうございます。

せっかくのご指摘ですが、
本Issueの対応範囲を超えたところでの問題点につきましては、
新たにIssueを作成いただいたほうがよろしいかと思いますが、いかがでしょうか。

**Comment by seiya-takano** [comment]
ご確認ありがとうございます。

>せっかくのご指摘ですが、
本Issueの対応範囲を超えたところでの問題点につきましては、
新たにIssueを作成いただいたほうがよろしいかと思いますが、いかがでしょうか。

確かにその通りですね。。
改めて別Issueとして挙げておきます。

その他、私からは確認事項ありませんので
本件はクローズをお願いします。

**Comment by jz4o** [comment]
>>せっかくのご指摘ですが、
本Issueの対応範囲を超えたところでの問題点につきましては、
新たにIssueを作成いただいたほうがよろしいかと思いますが、いかがでしょうか。
>
>確かにその通りですね。。
改めて別Issueとして挙げておきます。

上記、よろしくお願い致します。
本IssueはCloseしておきます。
