### ISSUE TITLE
Projectsのカラムを検討する

### ISSUE THREAD

**Issue by jz4o** [WitStudy/PMSystem#15]
現在使用している [Project](https://github.com/WitStudy/PMSystem/projects/1)のカラムは以下のとおりです。

- 残タスク
- 作業中
- 作業完了

上記Projectはテスト的に作成したものであり、
Project名やカラム名については、私が適当に決めたものとなっております。

本格的にProjectを使用する前に、
あらためてProject名／カラム名の検討を行っておいたほうが良くないでしょうか。

**Comment by seiya-takano** [comment]
>残タスク
作業中
作業完了
上記Projectはテスト的に作成したものであり、
Project名やカラム名については、私が適当に決めたものとなっております。

Issue作成ありがとうございます。
個人的には今の内容でも問題ないと感じていますが、せっかくなので意見を書いておきます。

・Project名
現状タスクの進捗管理以外で扱う予定がないのでそのままの名前で問題ないかと思いました。
別のProjectが発生する場合は名前の統一感が欲しいですね。

・カラム名
作業中にIssueが発生した場合、作業が止まり「作業中」に
タスクが溜まりやすくなってしまうかもしれません、「課題対応中」など
問題発生中を意味するカラムがあるとどのタスクがネックになっているか分かりやすいかと
思いました。（作業完了後に発覚したタスクをここに入れるかは微妙なところですが..）

ご検討お願い致します

**Comment by jz4o** [comment]
2017/09/27のミーティングにて検討しましたので、
私の方でProjectsのカラムを以下構成に修正致します。

- 残タスク
- 作業中
- 確認待ち
- フィードバック
- 作業完了

**Comment by jz4o** [comment]
Projectsのカラム構成を修正しましたので、確認をお願い致します。

**Comment by seiya-takano** [comment]
打合せで認識合わせしたとおりの
カラム構成となっていることを確認致しました。

**Comment by jz4o** [comment]
確認ありがとうございます。
問題ないようですので、本IssueをClose致します。
