### ISSUE TITLE
Wikiのタイトル募集

### ISSUE THREAD

**Issue by seiya-takano** [WitStudy/PMSystem#21]
現在、当システムのWiki名称
テスト的に付けたものがそのままになっています。

そろそろ本格的なWiki利用が始まりそうですので
正式な名称を募集したいと思います。
（特に候補出ないようであれば "Wiki" を採用したいと思います、、）

**Comment by jz4o** [comment]
まず確認させてください。
今回、対象となるページは[こちら](https://github.com/WitStudy/PMSystem/wiki)かと思いますが、
ページの各要素は以下の認識でよろしいでしょうか。

```
Home　　　　　←　ファイル名称

PMSyspedia　　←　Wiki名称

各リンク
```

**Comment by seiya-takano** [comment]
確認ありがとうございます。

>Home　　　　　←　ファイル名称
PMSyspedia　　←　Wiki名称
各リンク

上記の内容で認識しています。
が改めて見直すとWiki名称って必要なのか疑問に思えてきました。。「Tips」のような単語のほうがふさわしい気がします。

一般的にGitHubではWikiの名称があるものなのでしょうか？

**Comment by jz4o** [comment]
自分もWiki名称はなくて良いと思いました。

Wikiに名称がつけられているものは見たことがないです。。。
[rubocopのwiki](https://github.com/bbatsov/rubocop/wiki)を見た感じでは、「Tips」すら不要なのかもしれません。

**Comment by seiya-takano** [comment]
>Wikiに名称がつけられているものは見たことがないです。。。
rubocopのwikiを見た感じでは、「Tips」すら不要なのかもしれません。

そうでしたか、、
それでは、Wiki名称は無しの方向でいきたいと思います。
（該当記述は私のほうで削除しておきます。）

**Comment by jz4o** [comment]
よろしくお願い致します。

**Comment by seiya-takano** [comment]
対応完了しました。
ご確認よろしくお願いします。

**Comment by jz4o** [comment]
対応いただき、ありがとうございます。
該当の記載の削除を確認致しました。

**Comment by seiya-takano** [comment]
ご確認ありがとうございました。
本Issueクローズとさせていただきます。
