### ISSUE TITLE
開発環境構築手順を整備する

### ISSUE THREAD

**Issue by jz4o** [WitStudy/PMSystem#22]
少なくとも下記2点の修正が必要かと思います。

- ページ名と重複する見出しを削除する
- 「DB設定ファイルの作成」手順のファイル内容を修正する

その他、修正箇所がありましたら、ご指摘願えますでしょうか。

**Comment by seiya-takano** [comment]
Issue化ありがとうございます。

挙げられた2点修正必要だと思われますので対応お願い致します。
また、「Gemのインストール」項目の※以降の記述は不要ではないかと
感じました。

よろしければおねがいします。

**Comment by jz4o** [comment]
>「Gemのインストール」項目の※以降の記述は不要ではないかと
感じました。

ご指摘いただき、ありがとうございます。

上記も含めて対応いたしましたので、
ご確認のほど、よろしくお願い致します。

**Comment by seiya-takano** [comment]
各種修正が行われていることを確認しました。
ご対応ありがとうございました。

**Comment by jz4o** [comment]
ご確認いただき、ありがとうございます。
問題ないようですので、本IssueはCloseします
