### ISSUE TITLE
DB／モデルに制約を設ける

### ISSUE THREAD

**Issue by seiya-takano** [WitStudy/PMSystem#23]
記事表示機能に関わる最低限の項目として
タイトル・内容・作者を用意していますが、機能実装にあたり
それぞれ必須等必要な制約をDB+モデルへお願いできますでしょうか？

**Comment by jz4o** [comment]
タイトル・内容・作者に関しては、
いずれもNotNull制約のみで良いかと考えますが、問題ないでしょうか。

**Comment by seiya-takano** [comment]
問題ないと思われます。
よろしくお願い致します。

**Comment by jz4o** [comment]
対応しましたので、ご確認のほど、
どうぞよろしくお願い致します。

**Comment by seiya-takano** [comment]
各種NotNull制約が正しく設定されることを確認しました。
ご対応ありがとうございました。

**Comment by jz4o** [comment]
確認いただき、ありがとうございます。

問題ないとのことですが、モデルに文字数に関する制約がついておりませんでしたので、
追加で対応いたしました。

申し訳ありませんが、再確認のほど、
お願い致します。

**Comment by seiya-takano** [comment]
文字数制限の追加ありがとうございます。
こちら実際の表示文量が不明でしたので保留して
いましたが、必須だと思われますので本実装を
利用させていただきます。

**Comment by jz4o** [comment]
ご確認いただき、ありがとうございます。

記事テーブルは暫定的に作成したものですので、
今後、改めて、データ型や桁数などの検討が必要かと思います。

ひとまずはDBとモデルで最大文字数を合わせる形にしておりますので、
本IssueはCloseしておきます。
