### ISSUE TITLE
記事情報のCRUD処理を実装する

### ISSUE THREAD

**Issue by seiya-takano** [WitStudy/PMSystem#24]
記事表示に関わる最低限機能として
- 登録
- 表示
- 更新
- 削除

が必要かと思われます。
上記実装内容でよろしいでしょうか？

**Comment by jz4o** [comment]
Issueの登録、ありがとうございます。

内容に問題ありませんので、対応のほど、
どうぞよろしくお願い致します。

**Comment by seiya-takano** [comment]
記事機能のCRUD処理に関する最低限の画面実装を行いました。
ご確認よろしくお願いします。

また、各種レイアウトに関しては手を付けていない状態としています。
今後の実装方針を話し合う叩き台として利用していただければと
考えています。（#19 か新Issueにて改めて課題とします。）

**Comment by jz4o** [comment]
対応いただき、ありがとうございます。

レイアウトに関しては手をつけていないとのことですので、
表示に関しては本Issueの対象外と考えておられるかもしれませんが、
何点か確認させてください。

### 一覧画面

- 記事の内容は一覧に表示すべきか？

### 詳細画面

- 記事の各項目を横に並べる形で表示しているが、適切か？
- 記事の内容は単一行の表示で良いか？

### 入力画面(_form)

- 入力制限は不要か？

以上、どうぞよろしくお願い致します。

**Comment by seiya-takano** [comment]
ご検討ありがとうございます。

>### 一覧画面
>- 記事の内容は一覧に表示すべきか？

こちら現段階でも必要のない記述でした。修正致します。

>### 詳細画面
>- 記事の各項目を横に並べる形で表示しているが、適切か？
>- 記事の内容は単一行の表示で良いか？
>### 入力画面(_form)
>- 入力制限は不要か？

記事のボリューム感が分かりませんでしたので入力制限は行っていませんでしたが、#23 にて
文字数設定いただきましたので、そちらに合わせたフォームに修正致します。
ひとまず縦に項目を並べたものに修正したいと思いますがよろしいでしょうか？

**Comment by jz4o** [comment]
>ひとまず縦に項目を並べたものに修正したいと思いますがよろしいでしょうか？

詳細画面については、上記で問題ないかと思います。

<br>

修正のほど、どうぞよろしくお願い致します。

**Comment by seiya-takano** [comment]
修正遅くなり申し訳ありません。以下修正を行いましたので
ご確認よろしくお願いします。

- 一覧画面から内容表示削除
- 詳細画面の項目並びを調整
- 記事内容をsimple_formatで表示するよう修正
- 入力フォームに文字数制限を追加

また、各項目の表示幅に関しては適当なものとしていますので
ご自由に調整ください。

**Comment by jz4o** [comment]
修正いただき、ありがとうございます。

各項目の表示サイズは暫定的なもののようですし、
問題は特にないかと思います。

**Comment by seiya-takano** [comment]
ご確認ありがとうございました。
本Issueクローズとさせていただきます。
