### ISSUE TITLE
ドキュメントの記載箇所が不明

### ISSUE THREAD

**Issue by jz4o** [WitStudy/PMSystem#3]
現在、ドキュメントの記載箇所として、以下が存在しますが、
それぞれどのような内容を記載するか方針が決まっていません。
- README.md
- Wiki

<br>

個人的には以下のように使い分けてはどうかと思いますが、
いかがでしょうか。

## README.md
**対外的な内容**
- システム名
- システム概要
- リポジトリの目的
- etc.

## Wiki
**開発者向けの内容**
- 開発環境
- 開発環境構築手順
- タスク管理方法
- 仕様書（もし作る場合）
- etc.

**Comment by seiya-takano** [comment]
一般的に導入手順はREADMEに、使い方はWikiに書くイメージでしたがGithubでは
どうなんでしょうか？そもそもユーザ側で使う想定ではないかもしれませんが、
勘違いでしたらすみません。

一点、仕様書はWikiにまとめると乱雑になりそうに思うので、作成する場合は
分けたほうがいいのではと思います。（作ればですが、、）

また、これらのドキュメント自体も管理する必要があると思われますが、gitで
管理するものと考えてよろしいでしょうか？

ちなみに、英語で書かれる可能性ってありますか。。？

**Comment by jz4o** [comment]
>一般的に導入手順はREADMEに、使い方はWikiに書くイメージでしたがGithubでは
どうなんでしょうか？そもそもユーザ側で使う想定ではないかもしれませんが、

一般的にはそのイメージで良いのではないかと思います。
（ちなみに、GithubにおいてのREADMEは、宣伝としての役割も徐々に重要になっている模様です）

本リポジトリは、利用される想定がありませんでしたので、
READMEには、導入手順より、学習目的のリポジトリである旨を記載したほうが良いかと思いました。
（本リポジトリを訪れた利用者がまずREADMEを確認し、
　その後そっとページを閉じてくださるように。。。）

>一点、仕様書はWikiにまとめると乱雑になりそうに思うので、作成する場合は
>分けたほうがいいのではと思います。（作ればですが、、）
>
>また、これらのドキュメント自体も管理する必要があると思われますが、gitで
>管理するものと考えてよろしいでしょうか？

ひとまず本Issueでは仕様書については置いておきませんか？
（自分から挙げておいて申し訳ありませんが、
　作成するかすら決まっていないものの管理箇所を検討する意味はない気がします。）

>ちなみに、英語で書かれる可能性ってありますか。。？

日本語のみで良いと考えています。
ただし、英語の学習も兼ねるということでしたら、英語での記載もアリかと思います。

**Comment by seiya-takano** [comment]
>本リポジトリは、利用される想定がありませんでしたので、
READMEには、導入手順より、学習目的のリポジトリである旨を記載したほうが良いかと思いました。
（本リポジトリを訪れた利用者がまずREADMEを確認し、
　その後そっとページを閉じてくださるように。。。）

READMEの狙い承知しました。でしたら記載内容に異論ありません。

>ひとまず本Issueでは仕様書については置いておきませんか？

そうですね。仕様書に関しては決まってから再検討をお願いします。話が逸れすみません。
日本語が分かりにくく申し訳ないですが「また、これらのドキュメント～」以降は
README.mdのファイル自身に管理に関してでした（保管方法に関しても別件かもしれませんが、内容記述するうえで把握しておきたかったので、、）

>日本語のみで良いと考えています。

承知しました。どうか日本語だけでお願いします。。

**Comment by jz4o** [comment]
> READMEの狙い承知しました。でしたら記載内容に異論ありません。

ありがとうございます。

<br>


>>また、これらのドキュメント自体も管理する必要があると思われますが、gitで
管理するものと考えてよろしいでしょうか？
>
>日本語が分かりにくく申し訳ないですが「また、これらのドキュメント～」以降は
README.mdのファイル自身に管理に関してでした（保管方法に関しても別件かもしれませんが、内容記述するうえで把握しておきたかったので、、）

上記はREADME.mdの管理に関してでしたか。。。
README.mdはリポジトリのルートディレクトリに置いておく必要があるようです。
ですので、gitにて管理しておくのが良いかと思います。

ちなみに、Wikiに関してもgitで管理する認識です。
ただ、Wikiのリポジトリとソースコードのリポジトリは別物です。

- ソースコードのリポジトリ
  https://github.com/WitStudy/PMSystem.git

- Wikiのリポジトリ
  https://github.com/WitStudy/PMSystem.wiki.git

**Comment by seiya-takano** [comment]
>README.mdはリポジトリのルートディレクトリに置いておく必要があるようです。
ですので、gitにて管理しておくのが良いかと思います。

>ちなみに、Wikiに関してもgitで管理する認識です。
ただ、Wikiのリポジトリとソースコードのリポジトリは別物です。

いずれもgitでの管理とのこと承知しました。

>システム名
システム概要
リポジトリの目的
etc.

まだ開発の方針は固まっていませんが、書けそうな項目に関しては
タスクとして挙げてしまいますか？このあたりは今後の方針含め一度ミーティングを行いたいですね。

**Comment by jz4o** [comment]
>書けそうな項目に関してはタスクとして挙げてしまいますか？

対応できそうなものからやっていったほうが良いと思います。

本Issueで出てきた内容で、現時点で対応できそうなものは以下かと思いますが、いかがでしょうか
- READMEを整備する（別Issueを作成し対応）
  - システム概要を記載する
  - リポジトリの目的を記載する
  - 開発環境の記載を削除する
- Wikiに開発環境を記載する（別Issueを作成し対応）
- Wikiにタスク管理方法を記載する（ #1 にて対応）
- Wikiにドキュメント記載箇所の方針を記載する（ 本Issueにて対応 ）

<br>

>このあたりは今後の方針含め一度ミーティングを行いたいですね。

そうですね。Issueのやりとりだけではなかなか厳しいものを感じております。

**Comment by seiya-takano** [comment]
ありがとうございます。
それではミーティングの場を設けたいと思いますので後日改めて連絡させていただきます。

**Comment by jz4o** [comment]
どうぞよろしくお願い致します。

**Comment by jz4o** [comment]
2017/09/27のミーティングにて検討しましたので、
@seiya-takano にて以下対応をお願い致します。
-  READMEにシステム概要を記載する
- READMEにリポジトリの目的を記載する
- READMEから開発環境の記載を削除する
- Wikiに開発環境を記載する

なお、Wikiへのタスク管理方法の記載は #1 にて対応します。

**Comment by seiya-takano** [comment]
>READMEにシステム概要を記載する
READMEにリポジトリの目的を記載する
READMEから開発環境の記載を削除する
Wikiに開発環境を記載する

上記対応を行いました。
ご確認をよろしくお願いします。

**Comment by jz4o** [comment]
対応いただき、ありがとうございます。
対応内容に問題がないことを確認致しました。

**Comment by seiya-takano** [comment]
ご確認ありがとうございます。
本件クローズとさせていただきます。
