### ISSUE TITLE
ProjectsのCardをIssue化する

### ISSUE THREAD

**Issue by jz4o** [WitStudy/PMSystem#4]
#1 にてタスク管理方法を検討致しましたので、
以下のCardをIssue化してよろしいでしょうか。

- ドキュメンテーションを導入する
- コーディング規約を導入する
- テストコードを実装する
- マイページ機能を実装する
- 記事の外部連携機能を実装する
- コメント投稿機能を実装する
- いいね機能を作成する
- ユーザ機能を実装する
- 下書き機能（公開／非公開管理）機能を実装する
- タグ機能を実装する

**Comment by seiya-takano** [comment]
>・記事の外部連携機能
・タグ機能を実装

このあたりは以前のミーティングで要望レベルで出た内容と記憶していますが、
Issue化してしまい問題ありませんか？（実装するかの検討もIssue内で行うということでしょうか？）

**Comment by jz4o** [comment]
#1 にて、実装するかの検討はIssueで行うとしておりますので、
Issue化に問題は無いかと思います。

むしろ、対応の要否を検討せずにCardを作成してしまったことがよくありませんでした。
申し訳ありません。

Issue化する場合は、該当のCardを一度削除してしまったほうが良いかもしれません。
Issueで対応が必要となれば、あらためてCardを作成すれば良いだけですし。

**Comment by seiya-takano** [comment]
>#1 にて、実装するかの検討はIssueで行うとしておりますので、
Issue化に問題は無いかと思います。

承知いたしました。挙げられているCardのIssue化
よろしくお願いします。

>むしろ、対応の要否を検討せずにCardを作成してしまったことがよくありませんでした。
申し訳ありません。

確かに本来と順序が逆になってしまいましたね。上記のタスクはテスト的にCard化したものでしたし、Issueに本採用されたものは削除してしまいましょうか。

**Comment by jz4o** [comment]
承知致しました。
私の方で該当CardのIssue化及び削除を行っておきます。

**Comment by seiya-takano** [comment]
>私の方で該当CardのIssue化及び削除を行っておきます。

よろしくお願い致します。

**Comment by jz4o** [comment]
該当のCardのIssue化及び削除を行いましたので、確認をお願い致します。

**Comment by seiya-takano** [comment]
既存CardのIssue化/削除ありがとうございました。
漏れのないことを確認しました。

**Comment by jz4o** [comment]
確認いただき、ありがとうございます。
本IssueをCloseし、Cardも削除しておきます。
