### ISSUE TITLE
テストコードを実装する

### ISSUE THREAD

**Issue by jz4o** [WitStudy/PMSystem#7]
2017/08/10 のミーティングで出ていた要望です。

Issueにて対応要否を検討しないままCard化していたため、IssueにConvertしました。

**Comment by jz4o** [comment]
2017/09/27のミーティングにて検討しましたが、
現時点での検討は時期尚早との結論に至りましたので、本Issueはひとまず保留と致します。

**Comment by jz4o** [comment]
そろそろ対応できそう、とのことで合意がとれましたので、
私の方で、以下対応を行います。
- Jsonに関するファイル／処理の削除
    - views/**/*.json.jbuilder
    - controllerにおいてjsonを返す処理
- テストコードの導入
- テストコードの実装

**Comment by jz4o** [comment]
@seiya-takano 
対応を行いましたので、
ご確認のほど、よろしくお願いします。

**Comment by seiya-takano** [comment]
>Jsonに関するファイル／処理の削除
views/**/*.json.jbuilder
controllerにおいてjsonを返す処理
テストコードの導入
テストコードの実装

上記に関してレビューを行いました。
私の方で問題と感じる点はありませんでした。

ご対応ありがとうございました。

**Comment by jz4o** [comment]
ご確認いただき、ありがとうございます。
それでは本IssueはClose致します。
